### ISSUE TITLE
Myfitnesspal premium breaks script

### ISSUE THREAD

**Issue by KnobleChipmunk** [Surye/mfp-keto-userscript#1]
MFP Premium changes have disabled this script from working.

**Comment by Surye** [comment]
How so? It seems to be working the same for me. What are you seeing?

**Comment by KnobleChipmunk** [comment]
The food entry page remains the same and still works with my old macros, but the goals page has been changed so that I have to subscribe to premium before I can edit my macros in grams. Probably no way to get around this, but thought I'd mention it anyway.

http://imgur.com/a/94oU3

**Comment by osuvaldo90** [comment]
Ithian,

I don't believe that this script ever allowed you to enter macros by goal.
You may have it mistaken for a different script. I also used a script that
allowed me to set my macro goals by gram and can confirm that the MFP
changes have broken it. Please, correct me if I'm wrong.

**Comment by KnobleChipmunk** [comment]
Well that’s embarrassing. It’s been a while since I installed I forgot they were separate scripts. Please close this issue and thanks!

~Ithian

From: osuvaldo90
Sent: ‎Thursday‎, ‎May‎ ‎7‎, ‎2015 ‎8‎:‎08‎ ‎PM
To: Surye/mfp-keto-userscript
Cc: N DT

Ithian,

I don't believe that this script ever allowed you to enter macros by goal.
You may have it mistaken for a different script. I also used a script that
allowed me to set my macro goals by gram and can confirm that the MFP
changes have broken it. Please, correct me if I'm wrong.

**Comment by osuvaldo90** [comment]
I need to enter macros by gram also but I'd rather not pay for it. I will
look into creating a script for the new MFP and keep you updated.
