### ISSUE TITLE
Works in FF, not in Chrome

### ISSUE THREAD

**Issue by curiocious** [Surye/mfp-keto-userscript#11]
I'm not sure what I'm doing wrong, if anything, but I cannot get this script to work in Chrome. Set it up in Firefox using Greasemonkey with zero issues. Halp?

**Comment by BrendanKOz** [comment]
Have you tried using the Tampermonkey extension in Chrome?

**Comment by utdrmac** [comment]
Works well with Tampermonkey in Chrome. Mac OS X.10. Latest Chrome.
