### ISSUE TITLE
Net Carb in myfitness pal

### ISSUE THREAD

**Issue by misscin01** [Surye/mfp-keto-userscript#16]
I downloaded the code for google chrome on several of my computers and for some reason on my computer at work it started putting the net carb column at the front of the food diary and therefore not calculating, is there some  way to fix this?
![netcarb](https://cloud.githubusercontent.com/assets/20075820/16247696/db469adc-37bf-11e6-9dd4-9ccaec0026ea.jpg)

**Comment by Telluras** [comment]
I am having the same issue in myfitnesspal as well. Any word on a fix?

**Comment by tolgaek** [comment]
I think there was a recent update to myfitnesspal that broke this

**Comment by tolgaek** [comment]
I've submitted a fix for this ^

**Comment by misscin01** [comment]
Thank you.

**Comment by Surye** [comment]
Pulled in, should be available now.

**Comment by Telluras** [comment]
Thanks for the update and quick response! :)

**Comment by alisonmf** [comment]
Wow that was a fast response! I went on here to report the issue, and not only had it been reported, but already solved. Thank you!

**Comment by Telluras** [comment]
Confirmation, it is now working like a charm! Thank you so much for the fast response!

**Comment by irun2run** [comment]
Hi. I am still having this issue. I went to the master and pulled it in. I did not see an upgrade button anywhere.  I also shit down MFP and reloaded it. Help.  Thanks in advance.

**Comment by ghost** [comment]
I, also, am having this problem.  The script was working fine, yesterday.  Today, I am getting what is pictured above.  Repeatedly reinstalled the script; still the same issue.

**Comment by kiwifruit1** [comment]
Me too. MFP must have updated again :-(

**Comment by Surye** [comment]
@irun2run @kiwifruit1 @valyba #19 has the fix for this issue.

**Comment by kiwifruit1** [comment]
YAY!!!!! Thank you!!!!!!! :-)
