### ISSUE TITLE
Net Carb in Your Daily Goal line

### ISSUE THREAD

**Issue by Majcolorado** [Surye/mfp-keto-userscript#18]
Hi there, it looks like the Net Carb calculation on the Your Daily Goal line is incorrect. Here's a SS:

![image](https://cloud.githubusercontent.com/assets/20327722/16636055/edae5e60-4392-11e6-85aa-a6a3594c9dfe.png)

**Comment by Surye** [comment]
Working as intended, it would not make sense to subtract goal fiber from goal carbs. Set your goal carbs, and that is your net goal.
