### ISSUE TITLE
Upgrade problems.

### ISSUE THREAD

**Issue by neohdiver** [Surye/mfp-keto-userscript#19]
There is almost certainly something very basic I'm missing - but I have not been able to upgrade to the most recent version to fix the migrating and empty net carbs column.

The readme file directs me to, "Just visit https://github.com/Surye/mfp-keto-userscript/raw/master/mfpketo.user.js and click Upgrade."  Unfortunately when I follow the link, there is no "Upgrade" on that page to click.  I tried Reinstall (an option that is present) without success.  Post re-installing, it operates the same as before (with the Net carbs column ahead of the food item, filled with NaN.  I'm using Chrome - and it was working like a charm before the recent MFP changes.

I miss my Net Carbs column (that was working perfectly until MFP broke it).  thanks for any guidance you can provide!

ETA:  I have done a bit more exploration.  It appears I have the most recent version (1.9) installed, based on the update 19 days ago.

I'm still getting this:

![screenshot_071016_034707_pm](https://cloud.githubusercontent.com/assets/20375513/16715690/951fb002-46b5-11e6-8da1-8babebd0e280.jpg)

**Comment by mpatel514** [comment]
Same issue.  I did a diff and I have the same version on GitHub.

**Comment by alisonmf** [comment]
Under Armour must have pushed out another update – I'm seeing the same thing today.

**Comment by MelFischer** [comment]
I'm having the same issue today - was working fine yesterday. Also on Chrome.

**Comment by Croxy** [comment]
I am also seeing the same issue

**Comment by Surye** [comment]
Looks like they may be AB testing or something, I am not getting the update anymore. I think it's the g/% toggle feature. Either way I can't seem to reproduce the problem now. Will check back later.

**Comment by neohdiver** [comment]
Just now:

![screenshot_071216_015708_pm](https://cloud.githubusercontent.com/assets/20375513/16777692/873fdf6e-4838-11e6-983b-9e17f75be6be.jpg)

**Comment by Croxy** [comment]
Exactly what I'm getting.

**Comment by kiwifruit1** [comment]
Me too.

**Comment by tara20639** [comment]
I've had the same problem. I've uninstalled/reinstalled, but that didn't work.

**Comment by Surye** [comment]
Interesting, didn't do that when I was logged in, only if I log out.

**Comment by Surye** [comment]
3711d42 should fix these issues, let me know if 1.10 doesn't work.

**Comment by tara20639** [comment]
Thank you!!

JMJ
