### ISSUE TITLE
Mac MFP layout issue 

### ISSUE THREAD

**Issue by nybe** [Surye/mfp-keto-userscript#20]
having major problems with layout issues on both chrome and safari in Mac. 

See attached image:

[messed up MFP net carb layout.](http://i.imgur.com/kEkM0Wx.png)

**Comment by ghost** [comment]
I'm seeing the same issue in Firefox.  It started, a couple of days ago.  Was working fine, before

**Comment by ryanhallfayce** [comment]
Seeing this in chrome on Mac as well.

**Comment by revaewytak** [comment]
Seeing this in Chrome on Windows 10 also

**Comment by Surye** [comment]
Dupe of #19

**Comment by nybe** [comment]
thanks! much appreciated

**Comment by ghost** [comment]
Thank you!  It’s working for me, now.
