### ISSUE TITLE
NaNs even with the right columns

### ISSUE THREAD

**Issue by aaronrainbowhawk** [Surye/mfp-keto-userscript#21]
Terrific script, I learned about it a year ago from http://cavemanketo.com/configuring-mfp/ and had been using it actively for 6 months until an injury set me back. Coming back to it, I noticed when I'm logging food in My Fitness Pal, that all my Net Carbs entries say "NaN." I double checked that I had the right columns and I do – Carbs, Fiber, Fat, Protein, and Potassium.

Maybe there is some change they made at MFP that has interfered with this script?

Apologies if this is already a known issue. I'm new to Github. –Aaron

**Comment by Surye** [comment]
Make sure you're using version 0.10

**Comment by aaronrainbowhawk** [comment]
That was it, thanks Surye! I just needed to update the script via Tampermonkey.
