### ISSUE TITLE
With the script running I cannot save water consumption or food notes; also water consumption in ml won't save - shows NaN

### ISSUE THREAD

**Issue by as128** [Surye/mfp-keto-userscript#23]
Here's a video of the issues I'm having while the script is running: http://screencast.com/t/g5j05F4V3NL

With the script running:
1. Water consumption in ml shows NaN
2. I cannot save water consumption
3. I cannot save food notes
4. When I log in, sometimes I get a white screen with one line of text at the top (1:32 of the video)

Note at 1:10 of the video I change the water consumption to 200 ml and the food note to "test2" and it looks like it saved but when I log out and log back in at 2:03 of the video it shows water consumption as 850 ml and the food note as "test".

**Comment by arcwi** [comment]
I am also having the same issue. Any way of fixing this? Is this script even being maintained anymore? The only way I know to get around it is by disabling the script, adding the water, then re-enabling the script.

**Comment by Surye** [comment]
Sorry this has taken me so long to look at, was not using it for a while (and I never really track water...). In any case, should be fixed now.
