### ISSUE TITLE
Logging me off after editing/saving note in MFP

### ISSUE THREAD

**Issue by samanthannm** [Surye/mfp-keto-userscript#24]
When I have this enabled on MyFitnessPal, I get logged off after saving a food note in the diary. If I click "edit note" and click "save note," then the next thing I click on (anything from going to the next day to adding a new food entry) logs me off and sends me to the login screen. Once I log back in, I'm redirected to the link I clicked on (food diary or the next day). I am testing this in Chrome and I don't have the issue when I disable the script, but as soon as I re-enable it, I am having the logging off issue.

**Comment by ldnloveletters** [comment]
I also get this.  Exactly the same.  In Chrome and Safari.  Any fix for this?, as it is a really useful tool for keto but a shame that it doesn't allow you to make notes within MFP.

**Comment by Surye** [comment]
This should be fixed in the latest version, sorry for the delay. Can you please confirm (if you're still using it...)

**Comment by samanthannm** [comment]
Thanks, I tested and the issue has been resolved! Definitely a great tool.
