### ISSUE TITLE
How to resolve the negative net carb issue mentioned in FAQ

### ISSUE THREAD

**Issue by williamaquila** [Surye/mfp-keto-userscript#28]
The reason for negative net carb is because many of the food labels already shows net carb, like in Europe, and this is a big problem for users because of the inconsistency - some food labels shows total carbs, where some shows net carbs.

There's a simple way to correct this. 

The code can put in a simple logic, that if negative carbs are found, then simply disregard the calculated amount and use the original number of the carb as net carb. Problem solved. 

This will make the script much more popular

**Comment by aikar** [comment]
PR open #31

**Comment by Surye** [comment]
PR #31 is how I want to solve this, if the entry does not mention net carbs, I don't want to make assumptions about the data. There's a lot of bad data in MFP, and there are cases where fiber = 3, carbs = 10, net could be 7 or 10 if left ambiguous, negative entries could be bad data or mislabeled.
