### ISSUE TITLE
fats not showing on daily totals pie chart

### ISSUE THREAD

**Issue by blissfulbabe** [Surye/mfp-keto-userscript#29]
I get this message: Daily Totals by Calories (This is whatyou use for your macro ratios)Net CarbsProtein9%
but no fats showing.

Running this in FireFox and using version1.10.

Any help for a complete beginner would be appreciated (I didn't even know this was possible!)

**Comment by Surye** [comment]
Is this problem still happening with the new version? Please upgrade and check, thanks!
