### ISSUE TITLE
show net carbs in "your daily summary" (default home page)

### ISSUE THREAD

**Issue by zevaverbach** [Surye/mfp-keto-userscript#30]
<img width="633" alt="screen shot 2017-04-11 at 2 41 51 pm" src="https://cloud.githubusercontent.com/assets/2838836/24925073/123e25cc-1ec5-11e7-918e-b861b4fe9327.png">

**Comment by Surye** [comment]
This would need to be a separate script, and the script can only calculate based on the data on the page, and this page doesn't have fiber (and wouldnt calculate correctly for "net carb" food entries) so this is unfortunately not doable.
