### ISSUE TITLE
NaN showing in Total Carbs Column 

### ISSUE THREAD

**Issue by garryweil** [Surye/mfp-keto-userscript#35]
Just installed on Chrome 58.0.3029.110 on Windows 10. The Total Carb column is showing NaN expect for the daily totals.
![image](https://user-images.githubusercontent.com/28911093/27117047-8c4f2ae6-5089-11e7-9a02-c87768847171.png)

**Comment by Surye** [comment]
Do you have the Fiber column displayed?

**Comment by garryweil** [comment]
Yes, sorry I made the change on my mobile but not on the web version. Now all is well!
Thanks
