### ISSUE TITLE
Net Carbs Remaining showing Carbs Daily Goal rather than Net Carbs Remaining

### ISSUE THREAD

**Issue by squashmcdermott** [Surye/mfp-keto-userscript#37]
see [link](http://imgur.com/AwAjUyk). _Net Carbs: Remaining_ should be _Your Daily Goal: Carbs_ minus _Total: Net Carbs_ right?

**Comment by Surye** [comment]
There was a bug where the total wasn't tracking the "already included fiber" from "net carb" food entries. It should be fixed now.
