### ISSUE TITLE
Greasemonkey for Firefox not compatible with v.57+, use Tampermonkey instead

### ISSUE THREAD

**Issue by MikeRatcliffe** [Surye/mfp-keto-userscript#38]
In README.md you suggest installing Greasemonkey for Firefox but it is not compatible with Firefox 57 and above. Please add a not to say that for v57 and above people should install Tampermonkey from https://addons.mozilla.org/firefox/addon/tampermonkey/.

**Comment by Surye** [comment]
Just going to recommend Tampermonkey in general now, it's a better solution. If you prefer Greasemonkey, you don't need instructions :P
