### ISSUE TITLE
The script has suddenly stopped working today

### ISSUE THREAD

**Issue by Lambo91** [Surye/mfp-keto-userscript#40]
I have just reinstalled the script and reopened my browser but no joy.

Also it shows the script as installed but then says no script running. What should I do?

![image](https://user-images.githubusercontent.com/31828889/30252245-5b1f7ade-9666-11e7-8de6-aaab2a6ab231.png)

The net carbs option is not showing up on the columns:

![image](https://user-images.githubusercontent.com/31828889/30252252-8cf1a672-9666-11e7-9e73-b41c1dc02df6.png)

**Comment by Surye** [comment]
I know it's been a while, but for anyone else looking here, it adds it to the diary page, but it will not be in the Settings page.
