### ISSUE TITLE
Show Net Carbs under Your Daily Goal at bottom of food diary page

### ISSUE THREAD

**Issue by rclewen** [Surye/mfp-keto-userscript#41]
In the table at the bottom of the diary page, the entries for Net Carbs and Carbs in the Your Daily Goal row are the same. It would be great if this showed net carbs.

Thanks for a great add-on to MFP!

![2017-09-22 14_20_14-rclewen s food diary _ myfitnesspal com](https://user-images.githubusercontent.com/24443095/30760891-c134d226-9fa1-11e7-8b0b-7a4f72460786.jpg)

**Comment by Surye** [comment]
The intent is to set your goal to your net goal. Because this would be a calculation based on Fiber goal otherwise, and that might not be what you want.
