### ISSUE TITLE
net carbs not adding up correctly

### ISSUE THREAD

**Issue by tonyabeckman** [Surye/mfp-keto-userscript#45]
Net carbs totals sometimes doesn't add up correctly.
![untitled](https://user-images.githubusercontent.com/37414475/37477860-238b8204-284f-11e8-9822-8684e974b94b.jpg)

**Comment by Surye** [comment]
There was a bug where the total wasn't tracking the "already included fiber" from "net carb" food entries. It should be fixed now.
