### ISSUE TITLE
Negative net carbs

### ISSUE THREAD

**Issue by wickywoo0284** [Surye/mfp-keto-userscript#46]
My net carbs are adding up to a negative number

<img width="1064" alt="screen shot 2018-04-03 at 9 31 48 am" src="https://user-images.githubusercontent.com/21371270/38262452-189ba93c-3722-11e8-9730-fe93f7f3f977.png">

**Comment by cnanney** [comment]
@wickywoo0284 The Keto Chow has more fiber than carbs which is likely wrong, so the final totals calculation for net carbs ends up being `carbs (8) minus fiber (18) = -10`.

However, looks like the food rows and meal totals just display net carbs as carbs if carbs < fiber.

**Comment by Surye** [comment]
There was a bug where the total wasn't tracking the "already included fiber" from "net carb" food entries. It should be fixed now.
