### ISSUE TITLE
Net Carbs Adding Up Incorrectly

### ISSUE THREAD

**Issue by apalcich1** [Surye/mfp-keto-userscript#49]
Please help! The net carbs are displaying as a higher count than total carbs. 
<img width="817" alt="screen shot 2019-01-08 at 12 16 36 pm" src="https://user-images.githubusercontent.com/46496739/50847104-ba89bd80-133e-11e9-9d7e-fd0694756256.png">

**Comment by Surye** [comment]
Check the FAQ about NaN... Fiber column 😁
