### ISSUE TITLE
Stopped working on Chrome today

### ISSUE THREAD

**Issue by Bferg23** [Surye/mfp-keto-userscript#53]
Script has worked for me for over a year. Stopped working today. Chrome Version 71.0.3578.98 (Official Build) (64-bit) Tried reinstall.

**Comment by dougwebb** [comment]
Not working on Firefox either. Maybe a change on the MFP website.

**Comment by Surye** [comment]
Not currently tracking on MFP, but I took a look and it seems to be working for me still:

![image](https://user-images.githubusercontent.com/109205/52094056-62775d00-2572-11e9-94aa-a9528eea01ba.png)

**Comment by Surye** [comment]
Updated Chrome as well, no change.
