### ISSUE TITLE
Numbers are still off

### ISSUE THREAD

**Issue by dsarah3** [Surye/mfp-keto-userscript#56]
Hi, I installed the updated script and now I am getting a 6% daily goal for net carbs, when it is set on MFP to 5%. The net carb totals are incorrect, also -- so far today I've had 21 g fiber, 22 g carbs, so it should read 1 net carb but says I had 4 net carbs. 

Just to test things a bit, I set my carb goals to 0%, and net carb goals came back as 1% -- so it was still 1% off. I set it back to 5%, and it reads a 6% goal.

Here are the screen shots, thanks in advance for your reply!:
<img width="625" alt="screen shot 2019-02-11 at 5 25 33 pm" src="https://user-images.githubusercontent.com/46941994/52605229-b7448e80-2e22-11e9-8910-01d1d7f9df25.png">
<img width="587" alt="screen shot 2019-02-07 at 1 04 25 am" src="https://user-images.githubusercontent.com/46941994/52605236-bdd30600-2e22-11e9-9fe9-fca6806c60e9.png">

**Comment by dsarah3** [comment]
Hi, I just noticed that my setting for 5% net carbs is correct on MFP UNTIL I ADD A FOOD! Once I add a food, the % changes to 6! Very odd. It was not doing that before. Any ideas? Thanks!

**Comment by ghost** [comment]
Hi Sarah,

I'm not sure why the % goal is wrong, although it might be a rounding error if you are specifying your goals in terms of grams. I've seen some discrepancies between the Android app and the website with some totals, and they seem to be rounding errors. I wouldn't be too concerned about a 1% discrepancy.

Also, I don't think the script has anything to do with the % values - they are calculated by MFP.

The other thing I noticed is that you don't seem to be using the modified version of the script I sent you. If you use my version, it changes the order of the columns:

![image](https://user-images.githubusercontent.com/46778681/52761121-e85cd300-305d-11e9-9b54-20c3f17c502d.png)

Perhaps try deleting the script entirely from Tampermonkey, then refresh the MFP website, then add the script again, save it, and refresh MFP website.

**Comment by dsarah3** [comment]
Yes, it was newbie-user error, you are 100% correct! For anyone who is reading this, the new script works!

**Comment by nicolecoffer34** [comment]
Can I get the updated Chrome version as well - the one I have is not calculating the fiber and net carbs...I already uninstalled the script i had and reinstalled it and that didn't work

![image](https://user-images.githubusercontent.com/57267859/68045243-4423c680-fc96-11e9-9607-331556f3fb6b.png)
