### ISSUE TITLE
mfp-keto-user 

### ISSUE THREAD

**Issue by dmcglown** [Surye/mfp-keto-userscript#58]
I tried to install the mfp-keto-userscript on my laptop. It appears to have installed yet I cannot see anything new (no pie chart, etc.) I am not paying for MFP. Did I do something wrong?

**Comment by dugchugger** [comment]
Did you install Tampermonkey and confirm the script shows up under "installed userscripts"?
Do you have the required columns selected in MFP ( carbs, fiber, fat, protein)?

**Comment by dmcglown** [comment]
Thanks, I finally got it to work

**Comment by dugchugger** [comment]
Awesome. Enjoy! :)
