### ISSUE TITLE
Addition of Net Carbs a Tad Off

### ISSUE THREAD

**Issue by loostraat** [Surye/mfp-keto-userscript#9]
Net carbs is showing 11g and should be 10g
![screen shot 2015-09-11 at 2 40 53 pm](https://cloud.githubusercontent.com/assets/14234865/9815191/7df86c26-5894-11e5-8b49-9d124d8cd867.png)

Net carbs is showing 18g and should be 16g.  Any suggestions on how to get the correct calculations?
![screen shot 2015-09-11 at 2 41 02 pm](https://cloud.githubusercontent.com/assets/14234865/9815185/780adf92-5894-11e5-8b5e-e8677080a2b1.png)

**Comment by Surye** [comment]
This is just calculated by doing Carbs - Fiber, what behavior are you expecting? 19-8 = 11, 23-5 = 18
